# Generated by Django 3.0.5 on 2021-03-15 08:05

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='polls',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'polls',
            },
        ),
        migrations.CreateModel(
            name='choice',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('choice_text', models.CharField(max_length=20)),
                ('votes', models.IntegerField(default=0)),
                ('question', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='polls.polls')),
            ],
            options={
                'db_table': 'choice',
            },
        ),
    ]
