# Generated by Django 3.0.5 on 2021-03-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='temp_password',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
